int Bfile_OpenFile_OS( const unsigned short*filename, int mode, int null );
int Bfile_CloseFile_OS( int HANDLE );
int Bfile_GetFileSize_OS( int handle, int pos );
int Bfile_SeekFile_OS( int handle, int pos );
int Bfile_ReadFile_OS( int HANDLE, void *buf, int size, int readpos );
int Bfile_CreateEntry_OS( const unsigned short*filename, int mode, int*size );
int Bfile_WriteFile_OS( int HANDLE, const void *buf, int size );
int Bfile_DeleteEntry( const unsigned short *filename );
void Bfile_StrToName_ncpy( unsigned short*dest, const unsigned char*source, int n );
int Bfile_FindFirst_NON_SMEM( const FONTCHARACTER *pathname, int *FindHandle, FONTCHARACTER *foundfile, FILE_INFO *fileinfo );
void Bfile_NameToStr_ncpy( unsigned char*source, const unsigned short*dest, int n );
int Bfile_FindNext_NON_SMEM( int FindHandle, FONTCHARACTER *foundfile, FILE_INFO *fileinfo );
int Bfile_FindClose( int FindHandle );
int Bfile_FindFirst( const FONTCHARACTER *pathname, int *FindHandle, FONTCHARACTER *foundfile, FILE_INFO *fileinfo );
int Bfile_FindNext( int FindHandle, FONTCHARACTER *foundfile, FILE_INFO *fileinfo );
int Bfile_RenameEntry( const unsigned short *oldname , const unsigned short *newname );
